language: python
dist: xenial
sudo: true
install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install -y python$TRAVIS_PYTHON_VERSION-dev
  - pip install -e .[tests,docs] tox-travis coveralls
matrix:
  include:
  - name: "Python 3.6"
    python: 3.6
  - name: "Python 3.8"
    python: 3.8
  - name: "Python 3.9"
    python: 3.9
script: pytest
after_success: if [ "${TRAVIS_PYTHON_VERSION}" == "3.9" ]; then coveralls; fi;
